import { Vendor, Post, User } from './types';

export const SEED_VENDORS: Vendor[] = [
  {
    id: '1',
    name: 'Shantamma Dosa Stall',
    slug: 'shantamma-dosa-stall',
    category: 'street_food',
    known_for: 'Ghee masala dosa',
    open_since: 1987,
    hours: '6:30 AM – 11 AM',
    price_range: '₹40–₹80',
    neighbourhood: 'Jayanagar 4th Block',
    city: 'Bangalore',
    lat: 12.9254,
    lng: 77.5823,
    status: 'verified',
    verification_count: 38,
    community_score: 9.4,
    daily_count: 247,
    daily_score: 9.4,
    total_rating_count: 1842,
    created_at: '2024-01-15T06:00:00Z',
  },
  {
    id: '2',
    name: 'Trupthi Mess',
    slug: 'trupthi-mess',
    category: 'mess_tiffin',
    known_for: 'Thali & ragi mudde',
    open_since: 2004,
    hours: '7 AM – 3 PM, 7 PM – 10 PM',
    price_range: '₹80–₹140',
    neighbourhood: 'Malleswaram 8th Cross',
    city: 'Bangalore',
    lat: 13.0037,
    lng: 77.5667,
    status: 'verified',
    verification_count: 24,
    community_score: 9.1,
    daily_count: 183,
    daily_score: 9.1,
    total_rating_count: 1204,
    created_at: '2024-02-10T06:00:00Z',
  },
  {
    id: '3',
    name: 'Idli Ashok',
    slug: 'idli-ashok',
    category: 'mess_tiffin',
    known_for: 'Rava idli',
    open_since: 1993,
    hours: '7 AM – 12 PM',
    price_range: '₹30–₹60',
    neighbourhood: 'MG Road, Brigade Junction',
    city: 'Bangalore',
    lat: 12.9762,
    lng: 77.6033,
    status: 'verified',
    verification_count: 31,
    community_score: 8.9,
    daily_count: 156,
    daily_score: 8.9,
    total_rating_count: 987,
    created_at: '2024-01-22T06:00:00Z',
  },
  {
    id: '4',
    name: 'Ramanna Chai',
    slug: 'ramanna-chai',
    category: 'chai_snacks',
    known_for: 'Masala chai',
    open_since: 2010,
    hours: '6 AM – 9 PM',
    price_range: '₹10–₹30',
    neighbourhood: 'Koramangala 5th Block',
    city: 'Bangalore',
    lat: 12.9352,
    lng: 77.6245,
    status: 'verified',
    verification_count: 19,
    community_score: 8.7,
    daily_count: 134,
    daily_score: 8.7,
    total_rating_count: 743,
    created_at: '2024-03-05T06:00:00Z',
  },
  {
    id: '5',
    name: 'Kamath Udupi',
    slug: 'kamath-udupi',
    category: 'restaurant',
    known_for: 'Bisi bele bath',
    open_since: 1978,
    hours: '8 AM – 10 PM',
    price_range: '₹120–₹250',
    neighbourhood: 'Indiranagar 12th Main',
    city: 'Bangalore',
    lat: 12.9784,
    lng: 77.6408,
    status: 'verified',
    verification_count: 42,
    community_score: 8.5,
    daily_count: 98,
    daily_score: 8.5,
    total_rating_count: 2156,
    created_at: '2023-12-01T06:00:00Z',
  },
  {
    id: '6',
    name: 'Sajjan Rava Bath',
    slug: 'sajjan-rava-bath',
    category: 'street_food',
    known_for: 'Khali dosa & chutney',
    open_since: 2019,
    hours: '7 AM – 11 AM',
    price_range: '₹20–₹50',
    neighbourhood: 'Basavanagudi',
    city: 'Bangalore',
    lat: 12.9435,
    lng: 77.5688,
    status: 'pending',
    verification_count: 1,
    community_score: 0,
    daily_count: 12,
    daily_score: 0,
    total_rating_count: 3,
    created_at: '2025-01-20T06:00:00Z',
  },
];

export const SEED_USER: User = {
  id: 'u1',
  username: 'arjun_blr',
  display_name: 'Arjun Sharma',
  city: 'Bangalore',
  bio: 'Eating my way through Bangalore since 2018',
  rating_count: 47,
  avg_score: 8.2,
  city_rank: 14,
  created_at: '2024-06-01T00:00:00Z',
};

export const SEED_RATED_VENDORS = [
  { vendor: SEED_VENDORS[0], personal_score: 1720, rank: 1, gps_verified: true, created_at: '2025-01-10T09:00:00Z' },
  { vendor: SEED_VENDORS[1], personal_score: 1685, rank: 2, gps_verified: true, created_at: '2025-01-08T12:00:00Z' },
  { vendor: SEED_VENDORS[2], personal_score: 1642, rank: 3, gps_verified: true, created_at: '2024-12-22T08:30:00Z' },
  { vendor: SEED_VENDORS[3], personal_score: 1598, rank: 4, gps_verified: false, created_at: '2024-12-15T17:00:00Z' },
  { vendor: SEED_VENDORS[4], personal_score: 1554, rank: 5, gps_verified: true, created_at: '2024-11-30T19:30:00Z' },
];

export const SEED_POSTS: Post[] = [
  {
    id: 'p1',
    user_id: 'u2',
    body: 'Finally found a dosa place that rivals my hometown in Udupi. Shantamma aunty\'s ghee masala dosa at 7am hits different 🔥',
    post_type: 'discovery',
    vendor_id: '1',
    like_count: 34,
    reply_count: 7,
    created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    user: {
      id: 'u2',
      username: 'priya_foodie',
      display_name: 'Priya Nair',
      city: 'Bangalore',
      rating_count: 82,
      created_at: '2024-01-01T00:00:00Z',
    },
    vendor: SEED_VENDORS[0],
  },
  {
    id: 'p2',
    user_id: 'u3',
    body: 'Looking for the best ragi mudde in Bangalore. Tried Trupthi Mess — anyone know somewhere better near Koramangala?',
    post_type: 'ask',
    like_count: 18,
    reply_count: 12,
    created_at: new Date(Date.now() - 5 * 3600000).toISOString(),
    user: {
      id: 'u3',
      username: 'karthik_blr',
      display_name: 'Karthik Reddy',
      city: 'Bangalore',
      rating_count: 29,
      created_at: '2024-03-15T00:00:00Z',
    },
  },
  {
    id: 'p3',
    user_id: 'u4',
    body: 'Just hit 50 ratings on Real Food Map 🎉 Took 8 months but I now have a proper personal food map of Bangalore. #milestone',
    post_type: 'milestone',
    like_count: 61,
    reply_count: 9,
    created_at: new Date(Date.now() - 11 * 3600000).toISOString(),
    user: {
      id: 'u4',
      username: 'deepa_tastes',
      display_name: 'Deepa Menon',
      city: 'Bangalore',
      rating_count: 51,
      created_at: '2023-10-01T00:00:00Z',
    },
  },
  {
    id: 'p4',
    user_id: 'u5',
    body: 'Kamath Udupi at Indiranagar has been consistent for 4 decades. Had their bisi bele bath this morning — absolute perfection.',
    post_type: 'discovery',
    vendor_id: '5',
    like_count: 29,
    reply_count: 4,
    created_at: new Date(Date.now() - 18 * 3600000).toISOString(),
    user: {
      id: 'u5',
      username: 'rohan_eats',
      display_name: 'Rohan Verma',
      city: 'Bangalore',
      rating_count: 63,
      created_at: '2024-04-20T00:00:00Z',
    },
    vendor: SEED_VENDORS[4],
  },
];
